###################################################################
# This script processes data from 
# /gsap/garage-protistvector/tstraub/ampseq/gtseq_v1/amp_frqs.rds
# generated by Tim Straub 30th Jan 2020 & accessed by Aimee on Feb 3rd 2020 via
# scp scp aimeet@login.broadinstitute.org:/gsap/garage-protistvector/tstraub/ampseq/gtseq_v1/amp_frqs.rds ~/Documents/
# 
# Tim's notes (copied from slack) : This file contains Senegal, 
# Columbia, French Guiana, and Mali data. For some amplicons, 
# there was no variation in some countries, so I put in Genotype.1 
# as a value of 1. A handful of amplicons had no useable SNP data and 
# they were excluded from this file 
# (PF3D7_1008700, PF3D7_1408100_1, PfHRP2_1, PfHRP3_1, and PvDHFR [vivax, not falciparum]). 
# To make it easier to separate out the CTSA amplicons (CSP, TRAP, SERA2, and AMA1) 
# from the regular gt-seq panel, those have a “z” pre-pended to their name and appear 
# on the bottom of the data set (e.g. zTRAP). The genotypes have bene 
# ordered based on decreasing allele frequency, just in case that makes a difference.
#
# All_Sanger_Amplicon_Haplotype_Frqs.Rdata          - haplotype frequencies for all three
# Columbia_Sanger_Amplicon_Haplotype_Frqs.Rdata	    - haplotype frequencies for Colombia
# FrenchGuiana_Sanger_Amplicon_Haplotype_Frqs.Rdata - haplotype frequencies for French Guiana
# Senegal_Sanger_Amplicon_Haplotype_Frqs.Rdata      - haplotype frequencies for Senegal	  
# combined_amp_frqs.txt                             - haplotype frequencies?
# combined_amp_frqs_sparse_matrix.txt               - haplotype frequencies?
#

###################################################################
rm(list = ls())
require(plyr) # for dlply

# Load data
amp_frqs = readRDS('../RData/amp_frqs.rds')

# Convert factors to character strings 
amp_frqs[] <- lapply(amp_frqs, function(x) if(is.factor(x)){as.character(x)}else{x})

# First separate amplicon data from country specific data 
amp_data = amp_frqs[!duplicated(amp_frqs$Amplicon_name), c('Amplicon_name','Chr','Start','Stop')]
rownames(amp_data) = amp_data$Amplicon_name

# Add median positions
amp_data$pos = apply(amp_data[,c('Start','Stop')], 1, function(x)median(as.numeric(x)))

# Add numeric chromosome
amp_data$chrom = as.numeric(gsub('_v3', '', gsub('Pf3D7_', '', amp_data$Chr)))
table(amp_data$chrom) # Check all chromosomes are represented: yes 

# Re-order data 
reordered_data_list = list()
for(chr in sort(unique(amp_data$chrom))){
  x = amp_data$pos[chr == amp_data$chrom] # Extract positions per chromosome 
  print(all(x == cummax(x))) # If not all True, not all are monotonically increasing
  inds = sort.int(x, index.return = T)$ix # Sort positions
  reordered_data_list[[chr]] = amp_data[chr == amp_data$chrom, ][inds, ]
}

# Check re-ordered data
amp_data = do.call(rbind, reordered_data_list)
all(sapply(unique(amp_data$chrom), function(chr){ # Check order
  x = amp_data$pos[chr == amp_data$chrom] 
  all(x == cummax(x)) 
}))

# Create distances
amp_data$dt <- c(diff(amp_data$pos), Inf)
pos_change_chrom <- 1 + which(diff(amp_data$chrom) != 0) # find places where chromosome changes
amp_data$dt[pos_change_chrom-1] <- Inf


# ************************ IMPORTANT ***************************
# After this next step, due to ordering of frequencies, the allele of
# "Genotype.1" in Amplicon #1 in Sengal may no longer be the 
# same allele as that of "Genotype.1" in Amplicon #1 in Colombia
# **************************************************************

# Separate by Country, order amplicons, order frequencies 
Genotypes = names(amp_frqs)[grepl('Genotype', names(amp_frqs))]
amp_order = amp_data$Amplicon_name
frqs_per_country = plyr::dlply(amp_frqs, 'Country', function(x){
  rownames(x) = x$Amplicon_name
  y = x[amp_order,] # Order amplicons
  z = t(apply(y[, Genotypes], 1, function(f) sort(as.numeric(f), decreasing = T))) # Order frequencies as numeric
})


# Save for reference
# save(amp_data,frqs_per_country, file = '../RData/GTseq_amp_data_for_IBDsim.RData')

# Remove CTSA 
CTSA = c("zTRAP","zSERA2","zCSP","zAMA1")
amp_data_rmCTSA = amp_data[!rownames(amp_data) %in% CTSA,]
frqs_per_country_rmCTSA = lapply(frqs_per_country, function(x){
  x[!rownames(x) %in% CTSA, ]
})

save(amp_data_rmCTSA, frqs_per_country_rmCTSA, file = '../RData/GTseq_amp_data_rmCTSA_for_IBDsim.RData')


