---
title: "paneljudge_multipanel_multicountry"
output: rmarkdown::html_vignette
 vignette: >
 %\VignetteIndexEntry{paneljudge_multipanel_multicountry}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
 ---
  
```{r, include = FALSE}
knitr::opts_chunk$set(
collapse = TRUE,
comment = "#>", 
fig.width = 12, fig.height = 12, fig.fullwidth = TRUE 
)
```

```{r setup}
rm(list = ls())
library(paneljudge)
require(RColorBrewer)
require(kableExtra)
```

```{r}
# Temporary hacks
devtools::load_all()
names(mles_CIs_sanger_barcode) <- c("Colombia", "French Guiana", "Senegal")
```

```{r specify colours and panels}
# =======================================================
# Colours and names of panels and countries
# =======================================================
# Manually name panels via palettes_panel: 
panels <- c("GTseq","GTseq_notCTSA","sanger_barcode","onlyCTSA")
cols_panels = RColorBrewer::brewer.pal(length(panels), 'Dark2')
names(cols_panels) <- panels

# Manually name countries via palettes_panel: 
palettes_countries = c("French Guiana" = 'YlGn', 
                       "Colombia" = 'YlOrRd', 
                       "Senegal" = 'YlGnBu', 
                       'Mali' = 'PuRd')

# Extract country names: 
countries = names(palettes_countries)
names(countries) <- countries # Name s.t. when used with lapply returns named list

# Specify ks and rs and name s.t. if used in lapply or sapply output is named
ks <- names(mles_CIs_GTseq$Colombia)
names(ks) <- ks
rs <- names(mles_CIs_GTseq$Colombia$`1`)
names(rs) <- rs
```

```{r extract CI lengths}
# =======================================================
# Extract CI lengths and rhat per panel 
# =======================================================
CI_lengths_rhat <- list()

CI_lengths_rhat$GTseq <- lapply(mles_CIs_GTseq, function(mles_country){
  lapply(mles_country, function(mles_k){
    lapply(mles_k, function(mles_r){
      sapply(mles_r, function(mles_i){
        # Upper and lower 95% CIs (CI colnames diff for non-default CIs)
        CI_length <- mles_i['rhat', '97.5%'] - mles_i['rhat', '2.5%'] 
        rhat <- mles_i['rhat', 'krhat'] # relatedness estimate
        return(c('CIlength' = CI_length, 'rhat' = rhat)) # End of fun. 
      })
    })
  })
})

CI_lengths_rhat$GTseq_notCTSA <- lapply(mles_CIs_GTseq_notCTSA, function(mles_country){
  lapply(mles_country, function(mles_k){
    lapply(mles_k, function(mles_r){
      sapply(mles_r, function(mles_i){
        # Upper and lower 95% CIs (CI colnames diff for non-default CIs)
        CI_length <- mles_i['rhat', '97.5%'] - mles_i['rhat', '2.5%'] 
        rhat <- mles_i['rhat', 'krhat'] # relatedness estimate
        return(c('CIlength' = CI_length, 'rhat' = rhat)) # End of fun. 
      })
    })
  })
})

CI_lengths_rhat$onlyCTSA <- lapply(mles_CIs_onlyCTSA, function(mles_country){
  lapply(mles_country, function(mles_k){
    lapply(mles_k, function(mles_r){
      sapply(mles_r, function(mles_i){
        # Upper and lower 95% CIs (CI colnames diff for non-default CIs)
        CI_length <- mles_i['rhat', '97.5%'] - mles_i['rhat', '2.5%'] 
        rhat <- mles_i['rhat', 'krhat'] # relatedness estimate
        return(c('CIlength' = CI_length, 'rhat' = rhat)) # End of fun. 
      })
    })
  })
})

CI_lengths_rhat$sanger_barcode <- lapply(mles_CIs_sanger_barcode, function(mles_country){
  lapply(mles_country, function(mles_k){
    lapply(mles_k, function(mles_r){
      sapply(mles_r, function(mles_i){
        # Upper and lower 95% CIs (CI colnames diff for non-default CIs)
        CI_length <- mles_i['rhat', '97.5%'] - mles_i['rhat', '2.5%'] 
        rhat <- mles_i['rhat', 'krhat'] # relatedness estimate
        return(c('CIlength' = CI_length, 'rhat' = rhat)) # End of fun. 
      })
    })
  })
})
```

```{r extract RMSEs}
# =======================================================
# Extract RMSE results per panel 
# =======================================================
RMSE <- list()

RMSE$GTseq <- lapply(mles_CIs_GTseq, function(mles_country){
  lapply(mles_country, function(mles_k){
    rs <- names(mles_k) # Character vector
    names(rs) <- rs # name s.t. RMSE is named on return
    sapply(rs, function(r){
      mles_r <- mles_k[[r]]
      RMSE <- sqrt(mean(sapply(mles_r, function(mles_i){
        (mles_i['rhat', 'krhat'] - as.numeric(r))^2
      })))
      return(RMSE)
    })
  })
})

RMSE$GTseq_notCTSA <- lapply(mles_CIs_GTseq_notCTSA, function(mles_country){
  lapply(mles_country, function(mles_k){
    rs <- names(mles_k) # Character vector
    names(rs) <- rs # name s.t. RMSE is named on return
    sapply(rs, function(r){
      mles_r <- mles_k[[r]]
      RMSE <- sqrt(mean(sapply(mles_r, function(mles_i){
        (mles_i['rhat', 'krhat'] - as.numeric(r))^2
      })))
      return(RMSE)
    })
  })
})

RMSE$onlyCTSA <- lapply(mles_CIs_onlyCTSA, function(mles_country){
  lapply(mles_country, function(mles_k){
    rs <- names(mles_k) # Character vector
    names(rs) <- rs # name s.t. RMSE is named on return
    sapply(rs, function(r){
      mles_r <- mles_k[[r]]
      RMSE <- sqrt(mean(sapply(mles_r, function(mles_i){
        (mles_i['rhat', 'krhat'] - as.numeric(r))^2
      })))
      return(RMSE)
    })
  })
})

RMSE$sanger_barcode <- lapply(mles_CIs_sanger_barcode, function(mles_country){
  lapply(mles_country, function(mles_k){
    rs <- names(mles_k) # Character vector
    names(rs) <- rs # name s.t. RMSE is named on return
    sapply(rs, function(r){
      mles_r <- mles_k[[r]]
      RMSE <- sqrt(mean(sapply(mles_r, function(mles_i){
        (mles_i['rhat', 'krhat'] - as.numeric(r))^2
      })))
      return(RMSE)
    })
  })
})
```

```{r extract CIs for k10}
# =======================================================
# Extract CIs for k = 10
# =======================================================
CIs_k10 <- list()

CIs_k10$GTseq <- lapply(mles_CIs_GTseq, function(per_country){
  per_country[["10"]]
})

CIs_k10$GTseq_notCTSA <- lapply(mles_CIs_GTseq_notCTSA, function(per_country){
  per_country[["10"]]
})

CIs_k10$onlyCTSA <- lapply(mles_CIs_onlyCTSA, function(per_country){
  per_country[["10"]]
})

CIs_k10$sanger_barcode <- lapply(mles_CIs_sanger_barcode, function(per_country){
  per_country[["10"]]
})



```

```{r re-order by country}
# =======================================================
# Re order lists by country
# Entries for Mali sanger_barcode will be NULL as of April 2020
# =======================================================
CI_lengths_rhat <- lapply(countries, function(country){
  lapply(CI_lengths_rhat, function(per_panel){
    per_panel[[country]]
  })})

RMSE <- lapply(countries, function(country){
  lapply(RMSE, function(per_panel){
    per_panel[[country]]
  })})

CIs_k10 <- lapply(countries, function(country){
  lapply(CIs_k10, function(per_panel){
    per_panel[[country]]
  })
})
```

```{r plot CI length all k, echo = F}
par(mfrow = c(2,2))
for(country in countries){
  
  # Extract CI lengths and rhat for country
  per_country <- CI_lengths_rhat[[country]]
  
  # Extract range of CI lengths for null plot ylim
  CI_length_range <- range(sapply(per_country, function(per_panel){
    sapply(per_panel, function(per_k){
      sapply(per_k, function(per_r){
        per_r['CIlength',]
      }) 
    })
  }))
  
  # Null plot CI length versus r for any k with panel overlaid
  plot(NULL, ylim = CI_length_range, xlim = c(0,1), 
       main = country, 
       ylab = 'Length of 95% confidence interval', 
       xlab = expression(hat(italic(r))))
  mtext(side = 3, text = 'All simulated k values', line = 0, cex = 0.5)
  legend('bottom', inset = 0.01, legend = panels, pch = 20, col = cols_panels[panels], 
         cex = 0.5)
  
  for(panel in panels){
    
    Y <- sapply(per_country[[panel]],function(per_k){
      sapply(per_k, function(per_r){
        per_r['CIlength',]
      })})
    
    X <- sapply(per_country[[panel]],function(per_k){
      sapply(per_k, function(per_r){
        per_r['rhat',]
      })})
    
    # Plot CI length versus r for any k
    points(y = as.vector(Y),
           x = as.vector(X), 
           pch = 20, 
           col = adjustcolor(cols_panels[panel], alpha.f = '0.5'))
  }
}
```




```{r plot CI length per k, echo = F}
# =======================================================
# Plot CI lengths and rhat per country coloured by panel
# (for all k combined)
# =======================================================
par(mfrow = c(length(ks), length(countries)))

for(country in countries){
  
  # Extract countries
  per_country <- CI_lengths_rhat[[country]]
  
  # Re_organise s.t. k before panel
  per_country <- lapply(ks, function(k){
    lapply(per_country, function(per_panel){
      per_panel[[k]]
    })
  })
  
  for(k in ks){
    
    # Extract range of CI lengths for null plot ylim
    CI_length_range <- range(sapply(per_country[[k]], function(per_panel){
      sapply(per_panel, function(per_r){
        per_r['CIlength',]
      }) 
    }))
    
    # Null plot CI length versus r for any k with panel overlaid
    plot(NULL, ylim = CI_length_range, xlim = c(0,1), 
         main = country, 
         ylab = 'Length of 95% confidence interval', 
         xlab = expression(hat(italic(r))))
    mtext(side = 3, text = k, line = 0, cex = 0.5)
    legend('bottom', inset = 0.01, legend = panels, pch = 20, 
           col = cols_panels[panels], cex = 0.5)
    
    for(panel in panels){
      
      Y <- sapply(per_country[[k]][[panel]],function(per_r){
        per_r['CIlength',]
      })
      
      X <- sapply(per_country[[k]][[panel]], function(per_r){
        per_r['rhat',]
      })
      
      # Search for names using paste s.t. k=1 doesn't return k=10 etc. 
      ind <- which(grepl(paste(k, ''), names(Y)))
      
      # Plot CI length versus r for any k
      points(y = as.vector(Y),
             x = as.vector(X), 
             pch = 20, 
             col = adjustcolor(cols_panels[panel], alpha.f = '0.5'))
    }
  }}
```

```{r plot RMSE all ks, echo = F}
# =======================================================
# Plot RMSE against rhat per country coloured by panel
# (for all k combined)
# =======================================================
par(mfrow = c(2,2))

for(country in countries){
  
  # Extract CI lengths and rhat for country
  per_country <- RMSE[[country]]
  
  # Extract range of CI lengths for null plot ylim
  RMSE_range <- range(sapply(per_country, function(per_panel){
    sapply(per_panel, function(per_k){
      range(per_k)
    })
  }))
  
  
  # Null plot CI length versus r for any k with panel overlaid
  plot(NULL, ylim = RMSE_range, xlim = c(0,1), 
       main = country, 
       ylab = 'RMSE', 
       xlab = expression(hat(italic(r))))
  mtext(side = 3, text = 'All simulated k values', line = 0, cex = 0.5)
  legend('bottom', inset = 0.01, cex = 0.5, 
         legend = c(panels, paste('k =', ks )),
         pch = c(rep(NA, length(panels)), 1:length(ks)),
         lty = c(rep(1, length(panels)), rep(NA, length(ks))),
         col = c(cols_panels[panels], rep('#000000', length(ks))))
  
  for(panel in panels){
    
    per_panel <- per_country[[panel]]
    
    for(k in ks){
      # Plot CI length versus r for any k
      points(y = per_panel[[k]],
             x = as.numeric(names(per_panel[[k]])), 
             pch = which(ks == k), type = 'b', 
             col = adjustcolor(cols_panels[panel], alpha.f = '0.5'))
    }
  }
}
```

```{r plot RMSE lengths per k, echo = F}
# =======================================================
# Plot RMSE against rhat per country coloured by panel per k
# =======================================================
par(mfrow = c(length(ks),length(countries)))


for(country in countries){
  
  # Extract countries
  per_country <- RMSE[[country]]
  
  # Re_organise s.t. k before panel
  per_country <- lapply(ks, function(k){
    lapply(per_country, function(per_panel){
      per_panel[[k]]
    })
  })
  
  for(k in ks){
    
    # Extract range of CI lengths for null plot ylim
    RMSE_range <- range(unlist(per_country[[k]]))
    
    # Null plot CI length versus r for any k with panel overlaid
    plot(NULL, ylim = RMSE_range, xlim = c(0,1), 
         main = country, 
         ylab = 'RMSE', 
         xlab = expression(hat(italic(r))))
    mtext(side = 3, text = sprintf('k = %s', k), line = 0, cex = 0.5)
    legend('bottom', inset = 0.01, legend = panels, cex = 0.5, 
           lty = 'solid', col = cols_panels[panels])
    
    for(panel in panels){
      # Plot CI length versus r for any k
      points(y = per_country[[k]][[panel]],
             x = as.numeric(names(per_country[[k]][[panel]])), 
             pch = which(ks == k), type = 'b', 
             col = adjustcolor(cols_panels[panel], alpha.f = '0.5'))
      
    }
  }
}
```
```{r plot RMSE per panel, echo = F}
# Plot RMSE
par(mfrow = c(length(panels),length(countries)), mar = c(4,5,2,2), oma = rep(0,4), pty = 's')

for(country in countries){
  for(panel in panels){
    
    if(is.null(RMSE[[country]][[panel]])) {
      # Add null plot 
      plot(NULL, xlim = c(0,1), ylim = c(0,1), bty = 'n', xaxt = 'n', yaxt = 'n', ylab = '', xlab = '')
      
    } else {
      
      # Convert to matrix
      RMSEk_results <- sapply(RMSE[[country]][[panel]], function(x) x)
      
      rs = rownames(RMSEk_results)
      ks = colnames(RMSEk_results)
      cols_rs = brewer.pal(length(rs)+2, palettes_countries[country])[-(1:2)]
      cols_ks = brewer.pal(length(ks)+2, palettes_countries[country])[-(1:2)]
      
      # Error in the r parameter
      matplot(RMSEk_results, type = 'b', pch = 20, lty = 1, col = cols_ks, panel.fist = grid(), 
              ylab = expression('RMSE: relatedness,'~italic(r)), 
              xlab = expression('Relatedness,'~italic(r)), 
              xaxt = 'n', bty = 'n', main = country)
      axis(side = 1, at = 1:length(rs), labels = rs)
      legend('bottom', bty = 'n', lty = 1, pch = 20, col = cols_ks, inset = 0.05, cex = 0.5, 
             legend = ks, title = expression('Switch rate parameter,'~italic(k)))
      mtext(text = panel, line = -1, cex = 0.5)
    }
  }
}
```





```{r plot CIs, echo = F}
par(mfrow = c(length(countries),length(rs)), 
    mar = c(0,0,0,0), oma = c(4,4,2,2), 
    family = 'serif', pty = 'm')

for(country in countries){
  for(r in rs){
    for(panel in rev(panels)){
      
      # Extract results
      per_i = CIs_k10[[country]][[panel]][[r]]
      if (is.null(per_i)) next()
      
      restCIs = sapply(per_i, function(per_i) per_i['rhat',]) # Extract results for r
      
      # Order results
      Order = sort.int(restCIs['krhat',], index.return = T)$ix
      ADD = ifelse(country == countries[1], FALSE, TRUE)
      nrep <- ncol(restCIs)
      
      # Plot results
      if(panel == rev(panels)[1]){
        plot(NULL, pch = 20, ylim = c(0,1), xlim = c(1,nrep), 
             xaxt = 'n', yaxt = 'n', panel.first = grid())
      }
      polygon(x = c(1:nrep, nrep:1), 
              y = c(restCIs['2.5%', Order], rev(restCIs['97.5%', Order])),
              col = cols_panels[panel], border = NA)
      
      lines(restCIs['krhat',Order], col = 'white')
      abline(h = as.numeric(r), col = 'black')
      
      # Add title
      if(r == rs[1]){
        axis(side = 2, las = 1)
        title(main = country, line = -6)
      }
      
      # Add x-axis
      if(country == tail(countries, 1)){
        axis(side = 1, las = 1)
        title(xlab = 'Sample pair index')
      }
      
    } 
  }
}

# Add country legend: 
legend('bottom', bty = 'n', legend = panels, cex = 1.25,
       fill = cols_panels, inset = 0.01)
```

