# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

loglikelihood_cpp <- function(k, r, Ys, f, gendist, epsilon, rho) {
    .Call(`_paneljudge_loglikelihood_cpp`, k, r, Ys, f, gendist, epsilon, rho)
}

